### ISSUE TITLE
Images/placeholder are broken

### ISSUE THREAD

**Issue by dulvui** [noi-techpark/webcomp-tourism-detail#5]
In the WebComponentStore no images are shown.
On local machine placeholders are visible but when uploading to the store a broken image is shown.
Fixing issue #4 might fix this issue too.
@maximiliannocker

**Comment by Piiit** [comment]
@maximiliannocker The problem here is that our CDN does not support folders at the moment. So please flatten the "dist/img" folder into the "dist" folder, and adapt the code to that... Thx

I have added a pipeline step, that automatically updates the wcs-manifest.json to all files inside "dist", but only 1 level deep.
